# Generated by Django 4.2.2 on 2023-06-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedbacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("feedback", models.CharField(max_length=255)),
                ("recruiter", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Viewers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("viewer", models.CharField(max_length=255)),
                ("scroll_pos", models.CharField(max_length=255)),
                ("percent_scrolled", models.CharField(max_length=5)),
                ("reached_bottom", models.BooleanField(default=False)),
                ("device", models.CharField(max_length=255)),
                ("screen_size", models.CharField(max_length=255)),
                ("likes", models.CharField(max_length=255)),
                ("dislikes", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LikesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.viewers",
                    ),
                ),
            ],
        ),
    ]
