# Generated by Django 4.2.2 on 2023-06-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_viewers_device_alter_viewers_dislikes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likesmodel",
            old_name="user",
            new_name="viewer",
        ),
    ]
