# Generated by Django 4.2.2 on 2023-06-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_user_likesmodel_viewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="likesmodel",
            name="disliked",
            field=models.BooleanField(default=False),
        ),
    ]
