# Generated by Django 4.1.7 on 2023-06-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_likesmodel_disliked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="viewers",
            old_name="dislikes",
            new_name="views",
        ),
        migrations.RemoveField(
            model_name="viewers",
            name="likes",
        ),
    ]
